[tool.poetry]
name = "calc-work-time"
version = "0.1.0"
description = ""
authors = ["kohei kawazoe <a04272017@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
